<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        CATEGORY
* GENERATION DATE:  20.07.2021
* CLASS FILE:       /home/vmasideason/public_html/sql_class_generator/generated_classes/CATEGORY.php
* FOR MYSQL TABLE:  TBL_CATEGORY
* FOR MYSQL DB:     ryc_food_service
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.vmasideas.com
* -------------------------------------------------------
*
*/

require_once (__dir__ . "/Utils.php");

// **********************
// CLASS DECLARATION
// **********************

class CATEGORY implements JsonSerializable
{ // class : begin


    // **********************
    // ATTRIBUTE DECLARATION
    // **********************

    private $id_category;   // KEY ATTR. WITH AUTOINCREMENT

	private $id_category_parent;   // (normal Attribute)
	private $name;   // (normal Attribute)
	private $img_path;   // (normal Attribute)
	private $description;   // (normal Attribute)
	private $cat_order;   // (normal Attribute)
	private $id_status;   // (normal Attribute)
	private $creation_time;   // (normal Attribute)
	private $last_update_time;   // (normal Attribute)

    // **********************
	// CONSTRUCTOR METHOD
	// **********************

	public function __construct()
	{
		$a = func_get_args();
		$i = func_num_args();
		if (method_exists($this, $f = '__construct' . $i)) {
			call_user_func_array(array($this, $f), $a);
		}
	}

	public function __construct8($id_category_parent, $name, $img_path, $description, $cat_order, $id_status, $creation_time, $last_update_time)
	{
		try {
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a __construct8");
			$this->id_category_parent = $id_category_parent;
			$this->name = $name;
			$this->img_path = $img_path;
			$this->description = $description;
			$this->cat_order = $cat_order;
			$this->id_status = $id_status;
			$this->creation_time = $creation_time;
			$this->last_update_time = $last_update_time;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.INICIA.CATEGORY " . $ex);
			throw $ex;
		}
	}


    /**
	 * Constructor
	 * @abstract Se recibe el id del para obtener los demas de datos de db
	 * @param id id del objeto a construir
	 */
	public function __construct1($id)
	{
		try {
			global $log, $db, $IP;
			$this->id_category = $id;
			// $db->where("id_category", Utils::convUtf8($this->id_category));
			$db->where("id_category", $this->id_category);
			$obj = $db->get('TBL_CATEGORY');
			if ($db->count > 0) {
				$this->id_category_parent = $obj[0]["id_category_parent"];
				$this->name = $obj[0]["name"];
				$this->img_path = $obj[0]["img_path"];
				$this->description = $obj[0]["description"];
				$this->cat_order = $obj[0]["cat_order"];
				$this->id_status = $obj[0]["id_status"];
				$this->creation_time = $obj[0]["creation_time"];
				$this->last_update_time = $obj[0]["last_update_time"];
			} else {
				$log->trace("[$IP] Obj de clase CATEGORY no encontrada: " . $id);
			}
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CATEGORY.__construct1 " . $ex);
			throw $ex;
		}
	}

	// **********************
	// GETTER METHODS
	// **********************

	function getId_category()
	{
		return $this->id_category;
	}

	function getId_category_parent()
	{
		return $this->id_category_parent;
	}

	function getName()
	{
		return $this->name;
	}

	function getImg_path()
	{
		return $this->img_path;
	}

	function getDescription()
	{
		return $this->description;
	}

	function getCat_order()
	{
		return $this->cat_order;
	}

	function getId_status()
	{
		return $this->id_status;
	}

	function getCreation_time()
	{
		return $this->creation_time;
	}

	function getLast_update_time()
	{
		return $this->last_update_time;
	}

	// **********************
	// SETTER METHODS
	// **********************

	function setId_category($val)
	{
		$this->id_category =  $val;
	}

	function setId_category_parent($val)
	{
		$this->id_category_parent =  $val;
	}

	function setName($val)
	{
		$this->name =  $val;
	}

	function setImg_path($val)
	{
		$this->img_path =  $val;
	}

	function setDescription($val)
	{
		$this->description =  $val;
	}

	function setCat_order($val)
	{
		$this->cat_order =  $val;
	}

	function setId_status($val)
	{
		$this->id_status =  $val;
	}

	function setCreation_time($val)
	{
		$this->creation_time =  $val;
	}

	function setLast_update_time($val)
	{
		$this->last_update_time =  $val;
	}

	/**
	 * save
	 * @abstract Metodo para guardar un objeto nuevo
	 */
	public function save()
	{
		try {
			// creamos objeto de base datos
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a CATEGORY.save");

			

			$data = array(
                "id_category_parent" => $this->id_category_parent,
				"name" => $this->name,
				"img_path" => $this->img_path,
				"description" => $this->description,
				"cat_order" => $this->cat_order,
				"id_status" => $this->id_status,
				"creation_time" => $this->creation_time,
				"last_update_time" => $this->last_update_time
			);


			$id = $db->insert('TBL_CATEGORY', $data);

			if ($id) {
				$this->id_category = $id;
				return true;
			} else
				$log->error("[$IP] ERROR.CATEGORY.save " .  $db->getLastError());
				return false;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CATEGORY.save " . $ex);
			throw new Exception('Ocurrio un error al guardar los datos del objeto CATEGORY: ' . $db->getLastError());
		}
	}

	/**
	 * update
	 * @abstract Metodo para realizar la actualizacion de los datos de un objeto
	 */
	public function update()
	{
		try {

			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a CATEGORY.update");
			$data = array(
				"id_category_parent" => $this->id_category_parent,
				"name" => $this->name,
				"img_path" => $this->img_path,
				"description" => $this->description,
				"cat_order" => $this->cat_order,
				"id_status" => $this->id_status,
				"creation_time" => $this->creation_time,
				"last_update_time" => $this->last_update_time
			);

			$db->where("id_category", $this->id_category);

			if ($db->update('TBL_CATEGORY', $data)) {
				return true;
			} else
				throw new Exception('Error al actualizar los datos del objeto : ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CATEGORY.update " . $ex);
			throw $ex;
		}
	}


    /**
	 * deactivate
	 * @abstract Metodo para realizar la desactivacion del objeto
	 */
	public function deactivate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "2"
			);
			$db->where("id_category", $this->id_category);
			if ($db->update('TBL_CATEGORY', $data))
				return true;
			else
				throw new Exception('Error al desactivar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CATEGORY.deactivate " . $ex);
			throw $ex;
		}
	}


	/**
	 * activate
	 * @abstract Metodo para realizar la activación de la habitación
	 */
	public function activate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "1"
			);
			$db->where("id_category", $this->id_category);
			if ($db->update('TBL_CATEGORY', $data))
				return true;
			else
				throw new Exception('Error al activar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CATEGORY.activate " . $ex);
			throw $ex;
		}
	}

    /**
	 * Serializacion de objeto
	 */
	public function jsonSerialize()
	{
		return [
			"id_category" => $this->id_category,
			"id_category_parent" => $this->id_category_parent,
			"name" => $this->name,
			"img_path" => $this->img_path,
			"description" => $this->description,
			"cat_order" => $this->cat_order,
			"id_status" => $this->id_status,
			"creation_time" => $this->creation_time,
			"last_update_time" => $this->last_update_time
		];
	}
	

} // class : end

?>