<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        IMG
* GENERATION DATE:  20.07.2021
* CLASS FILE:       /home/vmasideason/public_html/sql_class_generator/generated_classes/TBL_CONSERVATION.php
* FOR MYSQL TABLE:  TBL_CONSERVATION
* FOR MYSQL DB:     ryc_food_service
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.vmasideas.com
* -------------------------------------------------------
*
*/

require_once (__dir__ . "/Utils.php");

// **********************
// CLASS DECLARATION
// **********************

class CONSERVATION implements JsonSerializable
{ // class : begin

    // **********************
    // ATTRIBUTE DECLARATION
    // **********************

    private $id_conservation;   // KEY ATTR. WITH AUTOINCREMENT

	private $id_variant;   // (normal Attribute)
	private $id_temperature;   // (normal Attribute)
	private $minimum;   // (normal Attribute)
	private $maximum;   // (normal Attribute)

    // **********************
	// CONSTRUCTOR METHOD
	// **********************

	public function __construct()
	{
		$a = func_get_args();
		$i = func_num_args();
		if (method_exists($this, $f = '__construct' . $i)) {
			call_user_func_array(array($this, $f), $a);
		}
	}

	public function __construct4($id_variant, $id_temperature, $minimum, $maximum)
	{
		try {
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a __construct4");
			$this->id_variant = $id_variant;
			$this->id_temperature = $id_temperature;
			$this->minimum = $minimum;
			$this->maximum = $maximum;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.INICIA.CONSERVATION " . $ex);
			throw $ex;
		}
	}


    /**
	 * Constructor
	 * @abstract Se recibe el id del para obtener los demas de datos de db
	 * @param id id del objeto a construir
	 */
	public function __construct1($id)
	{
		try {
			global $log, $db, $IP;
			$this->id_conservation = $id;
			// $db->where("id_img", Utils::convUtf8($this->id_img));
			$db->where("id_conservation", $this->id_conservation);
			$obj = $db->get('TBL_CONSERVATION');
			if ($db->count > 0) {
				$this->id_variant = $obj[0]["id_variant"];
				$this->id_temperature = $obj[0]["id_temperature"];
				$this->minimum = $obj[0]["minimum"];
				$this->maximum = $obj[0]["maximum"];
			} else {
				$log->trace("[$IP] Obj de clase CONSERVATION no encontrada: " . $id);
			}
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CONSERVATION.__construct1 " . $ex);
			throw $ex;
		}
	}

	// **********************
	// GETTER METHODS
	// **********************

	function getId_conservation()
	{
		return $this->id_conservation;
	}

	function getId_variant()
	{
		return $this->id_variant;
	}

	function getId_temperature()
	{
		return $this->id_temperature;
	}

	function getMinimum()
	{
		return $this->minimum;
	}

	function getMaximum()
	{
		return $this->maximum;
	}

	// **********************
	// SETTER METHODS
	// **********************

	function setId_conservation($val)
	{
		$this->id_conservation =  $val;
	}

	function setId_variant($val)
	{
		$this->id_variant =  $val;
	}

	function setId_temperature($val)
	{
		$this->id_temperature =  $val;
	}

	function setMinimum($val)
	{
		$this->minimum =  $val;
	}

	function setMaximum($val)
	{
		$this->maximum =  $val;
	}

	/**
	 * save
	 * @abstract Metodo para guardar un objeto nuevo
	 */
	public function save()
	{
		try {
			// creamos objeto de base datos
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a IMG.save");

			

			$data = array(
                "id_variant" => $this->id_variant,
				"id_temperature" => $this->id_temperature,
				"minimum" => $this->minimum,
				"maximum" => $this->maximum
			);


			$id = $db->insert('TBL_CONSERVATION', $data);

			if ($id) {
				$this->id_img = $id;
				return true;
			} else
				$log->error("[$IP] ERROR.CONSERVATION.save " .  $db->getLastError());
				return false;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CONSERVATION.save " . $ex);
			throw new Exception('Ocurrio un error al guardar los datos del objeto TBL_CONSERVATION: ' . $db->getLastError());
		}
	}

	/**
	 * update
	 * @abstract Metodo para realizar la actualizacion de los datos de un objeto
	 */
	public function update()
	{
		try {

			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a IMG.update");
			$data = array(
				"id_variant" => $this->id_variant,
				"id_temperature" => $this->id_temperature,
				"minimum" => $this->minimum,
				"maximum" => $this->maximum
			);

			$db->where("id_conservation", $this->id_conservation);

			if ($db->update('TBL_CONSERVATION', $data)) {
				return true;
			} else
				throw new Exception('Error al actualizar los datos del objeto : ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.CONSERVATION.update " . $ex);
			throw $ex;
		}
	}


    /**
	 * deactivate
	 * @abstract Metodo para realizar la desactivacion del objeto
	 */
	public function deactivate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "2"
			);
			$db->where("id_conservation", $this->id_conservation);
			if ($db->update('TBL_CONSERVATION', $data))
				return true;
			else
				throw new Exception('Error al desactivar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.TBL_CONSERVATION.deactivate " . $ex);
			throw $ex;
		}
	}


	/**
	 * activate
	 * @abstract Metodo para realizar la activación de la habitación
	 */
	public function activate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "1"
			);
			$db->where("id_conservation", $this->id_conservation);
			if ($db->update('TBL_CONSERVATION', $data))
				return true;
			else
				throw new Exception('Error al activar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.TBL_CONSERVATION.activate " . $ex);
			throw $ex;
		}
	}

    /**
	 * Serializacion de objeto
	 */
	public function jsonSerialize()
	{
		return [
			"id_conservation" => $this->id_conservation,
			"id_variant" => $this->id_variant,
			"id_temperature" => $this->id_temperature,
			"minimum" => $this->minimum,
			"maximum" => $this->maximum
		];
	}
	

} // class : end

?>