<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        IMG
* GENERATION DATE:  20.07.2021
* CLASS FILE:       /home/vmasideason/public_html/sql_class_generator/generated_classes/IMG.php
* FOR MYSQL TABLE:  TBL_IMG
* FOR MYSQL DB:     ryc_food_service
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.vmasideas.com
* -------------------------------------------------------
*
*/

require_once (__dir__ . "/Utils.php");

// **********************
// CLASS DECLARATION
// **********************

class IMG implements JsonSerializable
{ // class : begin


    // **********************
    // ATTRIBUTE DECLARATION
    // **********************

    private $id_img;   // KEY ATTR. WITH AUTOINCREMENT

	private $id_product;   // (normal Attribute)
	private $path;   // (normal Attribute)
	private $main_img;   // (normal Attribute)
	private $id_status;   // (normal Attribute)
	private $creation_time;   // (normal Attribute)
	private $last_update_time;   // (normal Attribute)

    // **********************
	// CONSTRUCTOR METHOD
	// **********************

	public function __construct()
	{
		$a = func_get_args();
		$i = func_num_args();
		if (method_exists($this, $f = '__construct' . $i)) {
			call_user_func_array(array($this, $f), $a);
		}
	}

	public function __construct6($id_product, $path, $main_img, $id_status, $creation_time, $last_update_time)
	{
		try {
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a __construct6");
			$this->id_product = $id_product;
			$this->path = $path;
			$this->main_img = $main_img;
			$this->id_status = $id_status;
			$this->creation_time = $creation_time;
			$this->last_update_time = $last_update_time;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.INICIA.IMG " . $ex);
			throw $ex;
		}
	}


    /**
	 * Constructor
	 * @abstract Se recibe el id del para obtener los demas de datos de db
	 * @param id id del objeto a construir
	 */
	public function __construct1($id)
	{
		try {
			global $log, $db, $IP;
			$this->id_img = $id;
			// $db->where("id_img", Utils::convUtf8($this->id_img));
			$db->where("id_img", $this->id_img);
			$obj = $db->get('TBL_IMG');
			if ($db->count > 0) {
				$this->id_product = $obj[0]["id_product"];
				$this->path = $obj[0]["path"];
				$this->main_img = $obj[0]["main_img"];
				$this->id_status = $obj[0]["id_status"];
				$this->creation_time = $obj[0]["creation_time"];
				$this->last_update_time = $obj[0]["last_update_time"];
			} else {
				$log->trace("[$IP] Obj de clase IMG no encontrada: " . $id);
			}
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.IMG.__construct1 " . $ex);
			throw $ex;
		}
	}

	// **********************
	// GETTER METHODS
	// **********************

	function getId_img()
	{
		return $this->id_img;
	}

	function getId_product()
	{
		return $this->id_product;
	}

	function getPath()
	{
		return $this->path;
	}

	function getMain_img()
	{
		return $this->main_img;
	}

	function getId_status()
	{
		return $this->id_status;
	}

	function getCreation_time()
	{
		return $this->creation_time;
	}

	function getLast_update_time()
	{
		return $this->last_update_time;
	}

	// **********************
	// SETTER METHODS
	// **********************

	function setId_img($val)
	{
		$this->id_img =  $val;
	}

	function setId_product($val)
	{
		$this->id_product =  $val;
	}

	function setPath($val)
	{
		$this->path =  $val;
	}

	function setMain_img($val)
	{
		$this->main_img =  $val;
	}

	function setId_status($val)
	{
		$this->id_status =  $val;
	}

	function setCreation_time($val)
	{
		$this->creation_time =  $val;
	}

	function setLast_update_time($val)
	{
		$this->last_update_time =  $val;
	}

	/**
	 * save
	 * @abstract Metodo para guardar un objeto nuevo
	 */
	public function save()
	{
		try {
			// creamos objeto de base datos
			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a IMG.save");

			

			$data = array(
                "id_product" => $this->id_product,
				"path" => $this->path,
				"main_img" => $this->main_img,
				"id_status" => $this->id_status,
				"creation_time" => $this->creation_time,
				"last_update_time" => $this->last_update_time
			);


			$id = $db->insert('TBL_IMG', $data);

			if ($id) {
				$this->id_img = $id;
				return true;
			} else
				$log->error("[$IP] ERROR.IMG.save " .  $db->getLastError());
				return false;
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.IMG.save " . $ex);
			throw new Exception('Ocurrio un error al guardar los datos del objeto IMG: ' . $db->getLastError());
		}
	}

	/**
	 * update
	 * @abstract Metodo para realizar la actualizacion de los datos de un objeto
	 */
	public function update()
	{
		try {

			global $log, $db, $IP;
			$log->trace("[$IP] Entrando a IMG.update");
			$data = array(
				"id_product" => $this->id_product,
				"path" => $this->path,
				"main_img" => $this->main_img,
				"id_status" => $this->id_status,
				"creation_time" => $this->creation_time,
				"last_update_time" => $this->last_update_time
			);

			$db->where("id_img", $this->id_category);

			if ($db->update('TBL_IMG', $data)) {
				return true;
			} else
				throw new Exception('Error al actualizar los datos del objeto : ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.IMG.update " . $ex);
			throw $ex;
		}
	}


    /**
	 * deactivate
	 * @abstract Metodo para realizar la desactivacion del objeto
	 */
	public function deactivate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "2"
			);
			$db->where("id_img", $this->id_img);
			if ($db->update('TBL_IMG', $data))
				return true;
			else
				throw new Exception('Error al desactivar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.IMG.deactivate " . $ex);
			throw $ex;
		}
	}


	/**
	 * activate
	 * @abstract Metodo para realizar la activación de la habitación
	 */
	public function activate()
	{
		try {
			global $log, $db, $IP;
			$data = array(
				"id_status" => "1"
			);
			$db->where("id_img", $this->id_img);
			if ($db->update('TBL_IMG', $data))
				return true;
			else
				throw new Exception('Error al activar el objeto: ' . $db->getLastError());
		} catch (Exception $ex) {
			$log->error("[$IP] ERROR.IMG.activate " . $ex);
			throw $ex;
		}
	}

    /**
	 * Serializacion de objeto
	 */
	public function jsonSerialize()
	{
		return [
			"id_img" => $this->id_img,
			"id_product" => $this->id_product,
			"path" => $this->path,
			"main_img" => $this->main_img,
			"id_status" => $this->id_status,
			"creation_time" => $this->creation_time,
			"last_update_time" => $this->last_update_time
		];
	}
	

} // class : end

?>