<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        STATUS
* GENERATION DATE:  20.07.2021
* CLASS FILE:       /home/vmasideason/public_html/sql_class_generator/generated_classes/STATUS.php
* FOR MYSQL TABLE:  CAT_STATUS
* FOR MYSQL DB:     ryc_food_service
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.vmasideas.com
* -------------------------------------------------------
*
*/

require_once (__dir__ . "/Utils.php");

// **********************
// CLASS DECLARATION
// **********************

class STATUS implements JsonSerializable
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

	private $id_status;   // KEY ATTR. WITH AUTOINCREMENT

	private $name;   // (normal Attribute)
	// **********************
	// CONSTRUCTOR METHOD
	// **********************

	public function __construct()
	{
		$a = func_get_args();
		$i = func_num_args();
		if (method_exists($this, $f = '__construct' . $i)) {
			call_user_func_array(array($this, $f), $a);
		}
	}

	public function __construct2($name,$dummy)
	{
        try 
		{
			global $log,$db,$IP;
			$log->trace("[$IP] Entrando a __construct2");   
            $this->name = $name;
        }
        catch(Exception $ex) 
		{
			$log->error("[$IP] ERROR.INICIA.STATUS ".$ex); 
            throw $ex;
        }
    }


	
	/**
     * Constructor
     * @abstract Se recibe el id del para obtener los demas de datos de db
     * @param id id del objeto a construir
     */
    public function __construct1($id) 
	{
        try 
		{
				global $log,$db,$IP;
				$this->id_status = $id;
				// $db->where("id_status",Utils::convUtf8($this->id_status));
				$db->where("id_status",$this->id_status);
				$obj = $db->get('CAT_STATUS');
				if ($db->count > 0)
				{		
						$this->name = $obj[0]["name"];
				}
				else
				{
						$log->trace("[$IP] Obj de clase STATUS no encontrada: ".$id); 
						
				}
        }
        catch(Exception $ex) 
		{
			$log->error("[$IP] ERROR.STATUS.__construct1 ".$ex); 
            throw $ex;
        }
    }
	
	// **********************
	// GETTER METHODS
	// **********************

	function getId_status()
	{
		return $this->id_status;
	}

	function getName()
	{
		return $this->name;
	}

	// **********************
	// SETTER METHODS
	// **********************

	function setId_status($val)
	{
		$this->id_status =  $val;
	}

	function setName($val)
	{
		$this->name =  $val;
	}

	/**
     * save
     * @abstract Metodo para guardar un objeto nuevo
    */
    public function save()
	{
        try 
		{
            // creamos objeto de base datos
			global $log,$db,$IP;
			$log->trace("[$IP] Entrando a STATUS.save");     	
			
			$data = Array (
			   	"name" => $this->name
				);
				 	
			$id = $db->insert ('CAT_STATUS', $data);
			
			if($id)
			{
				$this->id_status = $id;
				return true;
			}
			else
				return false;
        }
        catch(Exception $ex) 
		{
			$log->error("[$IP] ERROR.STATUS.save ".$ex); 
            throw new Exception('Ocurrio un error al guardar los datos del objeto STATUS: '.$db->getLastError());
        }
    }
	
	/**
     * update
     * @abstract Metodo para realizar la actualizacion de los datos de un objeto
    */
    public function update()
	{
        try {
            
			global $log,$db,$IP;
			$log->trace("[$IP] Entrando a STATUS.update");    
            $data = Array (
			   	"name" => $this->name
				);
			$db->where("id_status",$this->id_status);	
			
			if($db->update ('CAT_STATUS', $data))
			{				
				return true;
			}
				
			else
				 throw new Exception('Error al actualizar los datos del objeto : '.$db->getLastError());
        }
        catch(Exception $ex) 
		{
			$log->error("[$IP] ERROR.STATUS.update ".$ex); 
            throw $ex;
        }
    }
	
	/**
     * deactivate
     * @abstract Metodo para realizar la desactivacion del objeto
     */
    public function deactivate() {
        try {
			global $log,$db,$IP;
			$data = Array (
			   "id_status" => "2"
				);
			$db->where("id_status",$this->id_status);	
			if($db->update ('CAT_STATUS', $data))
				return true;
			else
				 throw new Exception('Error al desactivar el objeto: '.$db->getLastError());
        }
        catch(Exception $ex) 
		{
			 $log->error("[$IP] ERROR.STATUS.deactivate ".$ex);
             throw $ex;
        }
    }  
	
	
	/**
     * activate
     * @abstract Metodo para realizar la activación de la habitación
     */
    public function activate() 
	{
        try {
			global $log,$db,$IP;
			$data = Array (
			   "id_status" => "1"
				);
			$db->where("id_status",$this->id_status);	
			if($db->update ('CAT_STATUS', $data))
				return true;
			else
				 throw new Exception('Error al activar el objeto: '.$db->getLastError());
        }
        catch(Exception $ex) 
		{
			 $log->error("[$IP] ERROR.STATUS.activate ".$ex);
             throw $ex;
        }
    }  

	
	/**
     * Serializacion de objeto
     */
    public function jsonSerialize()
    {
        return [
				"id_status" => $this->id_status,
				"name" => $this->name
        ];
    }


} // class : end

?>